# Generated by Django 4.0.7 on 2022-09-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('parendId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_api.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('size', models.PositiveIntegerField()),
                ('parendId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_api.folder')),
            ],
        ),
    ]
