# Generated by Django 4.0.7 on 2022-09-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='parendId',
            new_name='parentId',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='parendId',
            new_name='parentId',
        ),
    ]
